config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  
  get 'users/new'
  get 'static_pages/nosotros'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :museums,             only: [:index, :create, :destroy]
  resources :stores
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  
  #Users relations
  has_many :microposts, dependent: :destroy
  has_many :museums, dependent: :destroy
  #indicating users haves many stores to create
  has_many :stores
  #relationships for user
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  
  #validation for users emails
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
    # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  def feedm
    Museum.where("user_id = ?", id)
  end
  
  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.all
  end
  
  def show
    @store = Store.new 
    
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @stores = Store.all
  end
  
  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Porfavor revise su correo para su activación."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
 
   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

  <h5 class="center">Registrate Gratis</h5>
  
  <div class="divider"></div>
  
  <div class="col l11 input-field ">
    <i class="material-icons prefix">person</i>
    <%= f.text_field :name, class: 'form-control' %>
    <label for="icon_prefix"><%= f.label :nombre %></label>
  </div>
  
  <div class=" col l11 input-field">
    <i class="material-icons prefix">email</i>
    <%= f.email_field :email, class: 'form-control' %>
    <label for="icon_prefix"><%= f.label :correo %></label>
  </div>
  
  <div class="col l11 input-field">
    <i class="material-icons prefix">lock_outline</i>
    <%= f.password_field :password, class: 'form-control' %>
    <label for="icon_prefix"><%= f.label :contraseña %></label>
  </div>
  
  <div class=" col l11 input-field">
    <i class="material-icons prefix">lock</i>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <label for="icon_prefix"><%= f.label :password_confirmation, "Confirma contraseña" %></label>
  </div>
  
  <div class="section">
    <div class="center">
      <%= f.submit "Registrarme", class: "waves-effect waves-light btn  link-rails hoverable z-depth-2 white-text " %>
    </div>
    <div class="center">
      <p>Ya tienes cuenta? <%= link_to "Inicia sesión", login_path%></p>
    </div>
  </div>
  
<% end %>

app/views/users/_user.html.erb
<li>
  
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="container valign-wrapper">
  <div class="row">
    <div class="col l6 offset-l3 ">
      <div class="card-panel z-depth-4 page-center">
        <h5 class="center">Actualizar Perfil</h5>
        
        <div class="divider"></div>
        
        <div class="section">
          <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
      
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
      
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
      
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
      
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
      
            <%= f.submit "Guardar Cambios", class: "waves-effect waves-light btn blue darken-4 hoverable z-depth-2 white-text" %>
          <% end %>
        </div>
      </div>
    </div>  
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h5 class="center">All users</h5>

<ul class="users">
  <% @users.each do |user| %>
    <li>
    <%= render user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container valign-wrapper">
  <div class="row">
    <div class="col l6 offset-l3 ">
      <div class="card-panel z-depth-4 page-center">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="card-panel container center-block">
  <%= @user.name %>, <%= @user.email %>
</div>


<div class="row">
  <div class="container">
    <div class="col l8 s12">
      <% if @user.microposts.any? %>
        
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
      <% end %>
    </div>
    <div class="section">
      <div class="col l4">
        <div class="card-panel micropost-border">

          <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Crear tienda</a>
          <div id="modal1" class="modal">
            <div class="modal-footer">
              <a class="modal-close waves-effect waves-green btn-flat"><i class="material-icons">
              clear</i></a>
            </div>
            <div class="modal-content">
              <%= render 'stores/form' %>
            </div>
          </div>
          <!--
           if @user.stores.any? %>
            <p>Numero de tiendas:  @user.stores.count</p>
           end -->
          
          <% @stores.each do |store| %>
            <ul>
              <% if current_user?(store.user) %>
                <li><%= link_to store.store_name %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
</div>

 