config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  
  get 'users/new'
  get 'static_pages/nosotros'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :museums,             only: [:index, :create, :destroy]
  resources :stores
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse ">
  
</header>
<% if logged_in? %>
<ul id="dropdown1" class="dropdown-content">
  <li><a>one</a></li>
   <li><%= link_to "Editar", edit_user_path(current_user) %></li>
  <li class="divider"></li>
  <%= link_to "Cerrar Sesión", logout_path, method: :delete, class:"black-text" %>
</ul>
<% end %>

<nav class="blue darken-3 z-depth-2">
  <div class="nav-wrapper container">
    <%= link_to "Tianguitz", root_path, class:"brand-logo" %> 
    <a href="#!"><img class="responsive-img " src="" width="150" height="150"></img></a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if logged_in? %>
      <li>
        <form action="" method="post" style="margin-top: 18px;">
          <div class="input-field">
            <input id="search" type="search" name="search" style="background-color: white;border-radius: 13px;">
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons exit-icon">close</i>
          </div>
        </form>
      </li>
      <li><%= link_to "Museo", museums_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><a class="dropdown-trigger"  data-target="dropdown1">Ajustes<i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
        <li><%= link_to "Iniciar Sesión", login_path, class:"waves-effect waves-light btn white black-text link-rails" %></li>
        <li><%= link_to "Nosotros", static_pages_nosotros_path %></li>
      <% end %>
    </ul>
  </div>
  
  <!--Navbar Mobile-->
  <% if logged_in? %>
    <ul class="sidenav" id="mobile-demo">
      <li><div class="user-view">
        <div class="background">
          <img src="https://res.cloudinary.com/craftwebs/image/upload/v1542849025/Arte-Mexicano-de-los-Siglos-XX-y-XXI-Courtesy-of-Museo-de-Arte-Moderno_vrvhkk.jpg">
        </div>
        <a href="#user"><img class="circle" src="https://res.cloudinary.com/craftwebs/image/upload/v1542848719/45474947_2015890855143215_1301709501136633856_n_ipd45h.jpg"></a>
        <a href="#name"><span class="white-text name">  </span></a>
        
        <a href="#email"><span class="white-text email">CEO en Cuantik</span></a>
      </div></li>
      <li>
        <form action="" method="post" autocomplete="off" style="margin-top: 18px;">
          <div class="input-field" autocomplete="off">
            <input id="search" autocomplete="off"  type="search" name="search" style="background-color: white;border-radius: 5px;">
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons exit-icon">close</i>
          </div>
        </form>
      </li>
      <li><a href="#!"><i class="material-icons teal-text text-accent-3">toys</i>Inicio</a></li>
      <li><a href="#!"><i class="material-icons teal-text text-accent-3">explore</i>Mapa</a></li>
      <li><a href="#!"><i class="material-icons teal-text text-accent-3">notifications<span class="badge">15</span></i>Notificaciones</a></li>
      
      <li><div class="divider"></div></li>
      
      <li><a class="sidenav-close"><i class="material-icons black-text">close</i> </a></li>
    </ul>
     
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tianguitz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <% flash.each do |message_type, message| %>
      <% if :warning && :success && :danger || :info  %>
        <script>
          $(function() {
            M.toast({html: "<%= message %>"}, 4000);
          });
        </script>
      <% end %>
    <% end %>
    
    <%= yield %>
  </body>
</html>